version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs-app
    overwrite: true

permissions:
  - object: /home/ubuntu/nodejs-app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: change_permissions.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu
